name: Build
on:
  - push
  - pull_request
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install CUDA toolkit
        uses: Jimver/cuda-toolkit@v0.2.9
        with:
          cuda: 12.1.0
          method: network
          sub-packages: '["nvcc"]'
          use-github-cache: true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
